pull_request_rules:
  - name: Automatically merge dependencies
    conditions:
      - base=master
      - label=dependencies
      - status-success=Docker Lint
      - status-success=Bats Test
      - status-success=Shell Lint
    actions:
      merge:
        strict: true
      delete_head_branch: {}
