on: push
name: Push
jobs:
  docker-lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Lint
      uses: docker://replicated/dockerfilelint
      with:
        args: Dockerfile
  bats-test:
    name: Bats Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bats Test
      uses: actions/bin/bats@master
      with:
        args: test/*.bats
  shell-lint:
    name: Shell Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Shell Lint
      uses: actions/bin/shellcheck@master
      with:
        args: entrypoint.sh
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
    - docker-lint
    - bats-test
    - shell-lint
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@master
    - name: Docker Build
      uses: actions/docker/cli@master
      with:
        args: build -t actions-yarn .
    - name: Docker Login
      uses: actions/docker/login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Docker Tag
      uses: actions/docker/tag@master
      with:
        args: actions-yarn culturehq/actions-yarn
    - name: Docker Push
      uses: actions/docker/cli@master
      with:
        args: push culturehq/actions-yarn
